function results = buildFFTAnalysisSoftware()
%BUILDFFTANALYSISSOFTWARE Build the FFT analysis app as a Windows executable.
%
% This build uses MATLAB Compiler. The generated executable requires
% MATLAB Runtime R2024b on machines that do not have MATLAB installed.

    projectRoot = fileparts(mfilename('fullpath'));
    outputRoot = fullfile(projectRoot, 'dist', 'FFTAnalysisApp');
    installerRoot = fullfile(projectRoot, 'dist', 'FFTAnalysisAppInstaller');

    additionalFiles = {
        fullfile(projectRoot, 'FourierAnalysisApp.m')
        fullfile(projectRoot, 'fftAnalyzeSignal.m')
        fullfile(projectRoot, 'readScopeCsv.m')
        fullfile(projectRoot, 'UI_README.md')
        fullfile(projectRoot, 'readme.md')
        };

    results = compiler.build.standaloneWindowsApplication( ...
        fullfile(projectRoot, 'runFourierAnalysisApp.m'), ...
        'ExecutableName', 'FFTAnalysisApp', ...
        'ExecutableVersion', '1.0.0.0', ...
        'AdditionalFiles', additionalFiles, ...
        'AutoDetectDataFiles', 'off', ...
        'SupportPackages', 'none', ...
        'EmbedArchive', 'on', ...
        'OutputDir', outputRoot, ...
        'Verbose', 'on');

    compiler.package.installer(results, ...
        'InstallerName', 'FFTAnalysisAppInstaller', ...
        'ApplicationName', 'FFT Analysis App', ...
        'Summary', 'MATLAB FFT and THD analysis app for MAT and oscilloscope CSV data.', ...
        'Description', 'Load MAT or oscilloscope CSV data, select signals, compute FFT and THD, preview waveforms, plot spectra, and export results.', ...
        'Version', '1.0', ...
        'RuntimeDelivery', 'web', ...
        'OutputDir', installerRoot, ...
        'Verbose', 'on');
end
